/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import controller.controller;
import model.mahasiswa;
import service.interface_mahasiswa;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author A S U S
 */
public class Mahasiswa extends javax.swing.JFrame {
    private interface_mahasiswa mahService;
    private DefaultListModel<String> listmodel;
   public mahasiswa selectedM;


  
    /**
     * Creates new form 
     */
    public Mahasiswa() {
        initComponents();
        mahService = new controller();
        setLocationRelativeTo(null);
        listmodel = new DefaultListModel<>();
     
        
          reload();
       
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        DetailMahasiswa = new javax.swing.JLabel();
        labelNIM = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelProdi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextPane1 = new javax.swing.JTextPane();
        namaT = new javax.swing.JTextPane();
        radio_if = new javax.swing.JRadioButton();
        radio_ds = new javax.swing.JRadioButton();
        radio_se = new javax.swing.JRadioButton();
        radio_it = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nimUpdate = new javax.swing.JTextPane();
        namaUpdate = new javax.swing.JTextPane();
        radio_ifupdate = new javax.swing.JRadioButton();
        radio_dsUpdate = new javax.swing.JRadioButton();
        radio_seUpdate = new javax.swing.JRadioButton();
        radio_itUpdate = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);
        jList1.getAccessibleContext().setAccessibleName("");

        DetailMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DetailMahasiswa.setText("Detail Mahasiwa");

        labelNIM.setText("NIM");

        labelNama.setText("Nama");

        labelProdi.setText("Prodi");

        jButton1.setText("Perbarui List");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Perbarui Data");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton5.setText("Hapus Data");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DetailMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelNIM)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelProdi)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelNama)
                                            .addGap(85, 85, 85)
                                            .addComponent(jLabel5)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton5)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DetailMahasiswa)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNIM)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNama)
                            .addComponent(jLabel5))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelProdi)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Daftar Mahasiswa", jPanel1);

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Prodi");

        radio_if.setText("IF");
        radio_if.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_ifActionPerformed(evt);
            }
        });

        radio_ds.setText("DS");
        radio_ds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_dsActionPerformed(evt);
            }
        });

        radio_se.setText("SE");
        radio_se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_seActionPerformed(evt);
            }
        });

        radio_it.setText("IT");
        radio_it.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_itActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radio_it)
                                    .addComponent(radio_if))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radio_ds)
                                    .addComponent(radio_se))))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaT, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(namaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radio_if)
                        .addComponent(radio_ds)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_se)
                    .addComponent(radio_it))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Input Mahasiswa", jPanel2);

        jLabel7.setText("NIM");

        jLabel8.setText("Nama");

        jLabel9.setText("Prodi");

        radio_ifupdate.setText("IF");
        radio_ifupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_ifupdateActionPerformed(evt);
            }
        });

        radio_dsUpdate.setText("DS");
        radio_dsUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_dsUpdateActionPerformed(evt);
            }
        });

        radio_seUpdate.setText("SE");
        radio_seUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_seUpdateActionPerformed(evt);
            }
        });

        radio_itUpdate.setText("IT");
        radio_itUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_itUpdateActionPerformed(evt);
            }
        });

        jButton4.setText("Simpan Update");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nimUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radio_itUpdate)
                                    .addComponent(radio_ifupdate))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radio_dsUpdate)
                                    .addComponent(radio_seUpdate))))
                        .addGap(75, 75, 75)))
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(nimUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(namaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radio_ifupdate)
                        .addComponent(radio_dsUpdate)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_seUpdate)
                    .addComponent(radio_itUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Deleted function", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        String nimUP = nimUpdate.getText();
        String namaUP = namaUpdate.getText();
        String prodiUP = radio_dsUpdate.isSelected() ? "DS" : radio_seUpdate.isSelected() ? "SE" : radio_itUpdate.isSelected() ? "IT" : radio_ifupdate.isSelected() ? "IF" : "";

        if(!nimUP.isEmpty() && !namaUP.isEmpty() && !prodiUP.isEmpty()){
            try{
                int id = selectedM.getId();
                mahasiswa mah = new mahasiswa(nimUP,namaUP,prodiUP,id);
                if(selectedM != null){
                    mahService.Update(mah);
                    JOptionPane.showMessageDialog(null, "Data berhasil di update!");
                    nimUpdate.setText("");
                    namaUpdate.setText("");
                    radio_dsUpdate.setSelected(false);
                    radio_seUpdate.setSelected(false);
                    radio_itUpdate.setSelected(false);
                    radio_ifupdate.setSelected(false);
                    reload();
                    jTabbedPane1.setSelectedIndex(0);
                }
            }catch (SQLException ex){
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Semua field harus diisi", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void radio_itUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_itUpdateActionPerformed
        // TODO add your handling code here:
        radio_dsUpdate.setSelected(false);
        radio_seUpdate.setSelected(false);
        radio_ifupdate.setSelected(false);
    }//GEN-LAST:event_radio_itUpdateActionPerformed

    private void radio_seUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_seUpdateActionPerformed
        radio_dsUpdate.setSelected(false);
        radio_ifupdate.setSelected(false);
        radio_itUpdate.setSelected(false);
    }//GEN-LAST:event_radio_seUpdateActionPerformed

    private void radio_dsUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_dsUpdateActionPerformed
        radio_ifupdate.setSelected(false);
        radio_seUpdate.setSelected(false);
        radio_itUpdate.setSelected(false);
    }//GEN-LAST:event_radio_dsUpdateActionPerformed

    private void radio_ifupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_ifupdateActionPerformed
        radio_dsUpdate.setSelected(false);
        radio_seUpdate.setSelected(false);
        radio_itUpdate.setSelected(false);
    }//GEN-LAST:event_radio_ifupdateActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String nim  = jTextPane1.getText();
        String nama = namaT.getText();
        String prodi = radio_se.isSelected() ? "SE" : radio_it.isSelected() ? "IT" : radio_if.isSelected() ? "IF" : radio_ds.isSelected() ? "DS": "";

        if(!nim.isEmpty() && !nama.isEmpty() && !prodi.isEmpty()){

            try{
                mahasiswa mah = new mahasiswa(nim,nama,prodi,0);
                mahService.input(mah);
                JOptionPane.showMessageDialog(null, "Data berhasil di input!");
                jTextPane1.setText("");
                namaT.setText("");
                radio_ds.setSelected(false);
                radio_if.setSelected(false);
                radio_se.setSelected(false);
                radio_it.setSelected(false);
                reload();
                jTabbedPane1.setSelectedIndex(0);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Semua field harus diisi", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void radio_itActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_itActionPerformed
        radio_ds.setSelected(false);
        radio_se.setSelected(false);
        radio_if.setSelected(false);
    }//GEN-LAST:event_radio_itActionPerformed

    private void radio_seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_seActionPerformed
        radio_ds.setSelected(false);
        radio_if.setSelected(false);
        radio_it.setSelected(false);
    }//GEN-LAST:event_radio_seActionPerformed

    private void radio_dsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_dsActionPerformed
        radio_if.setSelected(false);
        radio_se.setSelected(false);
        radio_it.setSelected(false);
    }//GEN-LAST:event_radio_dsActionPerformed

    private void radio_ifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_ifActionPerformed
        radio_ds.setSelected(false);
        radio_se.setSelected(false);
        radio_it.setSelected(false);
    }//GEN-LAST:event_radio_ifActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        int selectIndex = jList1.getSelectedIndex();

        if(selectIndex != -1){
            mahasiswa selectedNama = getSelectedMaha();
            try{
                mahService.delete(selectedNama.getNama());
                JOptionPane.showMessageDialog(null, "Mahasiswa dengan Nama " + selectedNama.getNama() + " berhasil dihapus.");
                reload();
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih mahasiswa yang ingin dihapus!");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        selectedM = getSelectedMaha();
        if(selectedM != null){
            //           jTabbedPane1.setSelectedIndex(2);
            nimUpdate.setText(selectedM.getNim());
            namaUpdate.setText(selectedM.getNama());
            switch(selectedM.getProdi()){
                case "IF" -> radio_ifupdate.setSelected(true);
                case "SE" -> radio_seUpdate.setSelected(true);
                case "IT" -> radio_itUpdate.setSelected(true);
                case "DS" -> radio_dsUpdate.setSelected(true);
            }
            dialog edit = new dialog(this,this,selectedM);
            edit.setVisible(true);

        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        reload();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        if(!evt.getValueIsAdjusting()){
            String selectedNama = jList1.getSelectedValue();
            if(selectedNama != null){
                try{
                    mahasiswa selectedMaha =  mahService.getNamebyNama(selectedNama);
                    if(selectedMaha != null){
                        jLabel4.setText(selectedMaha.getNim());
                        jLabel5.setText(selectedMaha.getNama());
                        jLabel6.setText(selectedMaha.getProdi());
                    }
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jList1ValueChanged
    
    private mahasiswa getSelectedMaha(){
        String selectedNama = jList1.getSelectedValue();
        if(selectedNama != null){
            try{
                return mahService.getNamebyNama(selectedNama);
            }catch(SQLException ex) {
                 JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            }
        }
        return null;
    }
    public void reload(){
        listmodel.clear();
        try{
       
         List<mahasiswa>  mahasiswal =  mahService.getAll();
         for(mahasiswa mah : mahasiswal){
             listmodel.addElement(mah.getNama());
         }
         jList1.setModel(listmodel);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }
   
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DetailMahasiswa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel labelNIM;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelProdi;
    private javax.swing.JTextPane namaT;
    private javax.swing.JTextPane namaUpdate;
    private javax.swing.JTextPane nimUpdate;
    private javax.swing.JRadioButton radio_ds;
    private javax.swing.JRadioButton radio_dsUpdate;
    private javax.swing.JRadioButton radio_if;
    private javax.swing.JRadioButton radio_ifupdate;
    private javax.swing.JRadioButton radio_it;
    private javax.swing.JRadioButton radio_itUpdate;
    private javax.swing.JRadioButton radio_se;
    private javax.swing.JRadioButton radio_seUpdate;
    // End of variables declaration//GEN-END:variables
  
}
